# Generated by Django 3.2.8 on 2024-03-21 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('cost', models.FloatField(default=0)),
                ('last', models.BooleanField(default=False)),
                ('token', models.CharField(default='-1', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='uploads/categories/')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CustomCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Luxury', 'Luxury'), ('Etnik', 'Etnik')], default='Luxury', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/collections/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('code', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('email', models.CharField(default='-1', max_length=256)),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('refund', models.CharField(default='No refund asked', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('code', models.CharField(default='', max_length=256)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, upload_to='uploads/products/')),
                ('s_image', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('amount_sold', models.IntegerField(default=0)),
                ('subtag', models.CharField(choices=[('ARRIBA', 'ARRIBA'), ('ABAJO', 'ABAJO'), ('VESTIDO', 'VESTIDO'), ('ACCESORIO', 'ACCESORIO')], default='ARRIBA', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('extra_tag', models.CharField(choices=[('WOMEN', 'WOMEN'), ('MEN', 'MEN'), ('KIDS', 'KIDS')], default='WOMEN', max_length=256)),
                ('available_colors', models.ManyToManyField(to='store_app.CustomColor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='store_app.category')),
                ('collection', models.ManyToManyField(related_name='products_per_collection_set', to='store_app.CustomCollection')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('css_cotent', models.TextField(blank=True, null=True)),
                ('js_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.TextField(blank=True, null=True)),
                ('section2', models.TextField(blank=True, null=True)),
                ('section3', models.TextField(blank=True, null=True)),
                ('section4', models.TextField(blank=True, null=True)),
                ('section5', models.TextField(blank=True, null=True)),
                ('section6', models.TextField(blank=True, null=True)),
                ('section7', models.TextField(blank=True, null=True)),
                ('section8', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.templates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('clothing_s', models.CharField(default='S', max_length=256)),
                ('size_of_sleeve', models.CharField(default='Corta', max_length=256)),
                ('fit', models.CharField(default='Regular Fit', max_length=256)),
                ('color', models.CharField(default='Default', max_length=256)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_set', to='store_app.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/products-images/')),
                ('type', models.CharField(default='first', max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='-1', max_length=256)),
                ('phone', models.CharField(default='-1', max_length=256)),
                ('address1', models.CharField(default='-1', max_length=256)),
                ('address2', models.CharField(default='-1', max_length=256)),
                ('user_first_name', models.CharField(default='-1', max_length=256)),
                ('user_last_name', models.CharField(default='-1', max_length=256)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(default='Ordered', max_length=256)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.cart')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='', max_length=256)),
                ('code', models.CharField(default='', max_length=256)),
                ('taken', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('POR CIENTO', 'POR CIENTO'), ('FIJO', 'FIJO')], default='POR CIENTO', max_length=256)),
                ('discount', models.FloatField(default=0.0)),
                ('how_many_items', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.cart')),
            ],
        ),
    ]
