# Generated by Django 3.2.8 on 2024-03-22 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='css_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='js_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to='store_app.templates'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
