# Generated by Django 3.2.8 on 2024-03-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20240322_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertemplate',
            old_name='css_content',
            new_name='css_cotent',
        ),
    ]
