# Generated by Django 3.2.8 on 2024-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_css_content_usertemplate_css_cotent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templates',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='usertemplate',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='templates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
