# Generated by Django 3.2.8 on 2024-03-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_auto_20240323_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertemplate',
            old_name='html_content4',
            new_name='html_content1',
        ),
    ]
