# Generated by Django 3.2.8 on 2024-03-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_coupon_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.TextField(blank=True, null=True)),
                ('section2', models.TextField(blank=True, null=True)),
                ('section3', models.TextField(blank=True, null=True)),
                ('section5', models.TextField(blank=True, null=True)),
                ('section6', models.TextField(blank=True, null=True)),
                ('section7', models.TextField(blank=True, null=True)),
                ('section8', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
