# Generated by Django 3.2.8 on 2024-03-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0027_websitetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetemplate',
            name='section4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
