# Generated by Django 3.2.8 on 2024-03-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_websitetemplate_section4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcollection',
            name='title',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Etnik', 'Etnik')], default='Luxury', max_length=256),
        ),
    ]
